from .cb_waiter import cb_waiter
from .navigation_waiter import navigation_waiter
from .select_waiter import select_waiter
from .count_waiter import count_waiter
from .cb_confirm import cb_confirm
from .basket_waiter import basket_waiter
from .cb_supplier import cb_supplier
from .navigation_supplier import navigation_supplier
from .select_supplier import select_supplier
from .single_waiter import single_waiter
from .add_product_waiter import add_product_waiter
from .orders_navigation import orders_navigation
from .confirm_supplier import confirm_supplier
from .basket_supplier import basket_supplier
from .choise_waiter import choise_waiter
from .navigation import navigation
