from .waiter_handler import dp
from .navigation_waiter_handler import dp
from .select_waiter import dp
from .count_waiter import dp
from .confirm import dp
from .cancel import dp
from .basket_waiter import dp
from .supplier_handler import dp
from .navigation_supplier_handler import dp
from .select_supplier import dp
from .delete_single import dp
from .add_product import dp
from .order_navigation import dp
from .basket_supplier import dp
from .choise_waiter_handler import dp
