# Generated by Django 4.0 on 2022-01-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_meal_options_alter_meal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='cost',
            field=models.FloatField(default=100, verbose_name='Cost'),
            preserve_default=False,
        ),
    ]
