# Generated by Django 4.0 on 2022-01-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_order_is_completed_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Completed'), (1, 'Pending'), (2, 'Canceled')], default=1, verbose_name='Status'),
        ),
    ]
