# Generated by Django 3.2.11 on 2022-01-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_orderitem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(null=True, verbose_name='Total'),
        ),
    ]
