# Generated by Django 3.2.11 on 2022-01-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_orderitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.IntegerField(null=True, verbose_name='Table number'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(default=0, verbose_name='Total'),
        ),
    ]
