# Generated by Django 3.2.11 on 2022-01-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_auto_20220113_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(null=True, verbose_name='Total'),
        ),
    ]
