# Generated by Django 3.2.11 on 2022-01-15 11:33

import apps.menu.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'Ovqat', 'verbose_name_plural': 'Ovqatlar'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Zakaz', 'verbose_name_plural': 'Zakazlar'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='YAratilgan sanasi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Bor narsa'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='menu.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='cost',
            field=models.FloatField(verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sanasi'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.menu.models.image_path, verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Bormi'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Tayyor'), (1, 'Kutmoqda'), (2, 'Qaytarilgan')], default=1, verbose_name='Status'),
        ),
    ]
