# Generated by Django 3.2.11 on 2022-01-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_auto_20220115_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Tayyor'), (1, 'Kutmoqda'), (2, 'Qaytarilgan'), (3, "To'landi")], default=1, verbose_name='Status'),
        ),
    ]
