# Generated by Django 3.2.11 on 2022-01-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payed',
            field=models.BooleanField(default=False, verbose_name="To'landi"),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Tugatildi'), (1, 'Kutmoqda'), (2, 'Qaytarilgan')], default=1, verbose_name='Status'),
        ),
    ]
