# Generated by Django 3.2.11 on 2022-01-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_auto_20220117_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(null=True, verbose_name='Price'),
        ),
    ]
