# Generated by Django 4.0 on 2022-01-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.IntegerField(choices=[(0, 'superuser'), (1, 'waiter'), (2, 'provider')], default=1, verbose_name='account role'),
        ),
    ]
