# Generated by Django 4.0 on 2022-01-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.IntegerField(choices=[(0, 'superuser'), (1, 'waiter'), (2, 'supplier')], default=1, verbose_name='account role'),
        ),
    ]
