# Generated by Django 3.2.11 on 2022-01-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sanasi'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Xodim'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=True, verbose_name='Super foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Familiyasi'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(db_index=True, help_text='9 ta raqam bolishi kerak, masalan: 979998877', max_length=9, unique=True, verbose_name='Raqami*'),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.IntegerField(choices=[(0, 'Super foydalanuvchi'), (1, 'Ofitsant'), (2, "Ta'minlovchi")], default=1, verbose_name='Foydalanuvchi huquqi'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sanasi'),
        ),
    ]
