# Generated by Django 3.2.11 on 2022-01-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0003_auto_20220115_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='price',
            field=models.FloatField(null=True, verbose_name='Narxi'),
        ),
    ]
