# Generated by Django 3.2.11 on 2022-01-15 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sklad', '0004_alter_productorder_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Miqdori')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sanasi')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklad.category', verbose_name='Kategoriya')),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oshpaz')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklad.product', verbose_name='Maxhsulot')),
            ],
            options={
                'verbose_name': 'Ishlatilgan Mahsulot',
                'verbose_name_plural': 'Ishlatilgan Mahsulotlar',
            },
        ),
    ]
