# Generated by Django 3.2.11 on 2022-01-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0005_usedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=100, max_digits=7, verbose_name='Miqdori'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productorder',
            name='quantity',
            field=models.FloatField(verbose_name='Miqdori'),
        ),
    ]
