# Generated by Django 3.2.11 on 2022-01-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0006_auto_20220116_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Miqdori'),
        ),
    ]
